lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls


urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)
    

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from django.core.exceptions import ValidationError

def home_page(request):
    return render(request, 'home.html')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    error = None

    if request.method == 'POST':
        try:
            item = Item.objects.create(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            error = "You can't have an empty list item"

    return render(request, 'list.html', {'list': list_, 'error': error})

def new_list(request):
    list_ = List.objects.create()
    item = Item.objects.create(text=request.POST['item_text'], list=list_)
    try:
    	item.full_clean()
    	item.save()
    except ValidationError:
    	list_.delete()
    	error = "You can't have an empty list item"
    	return render(request, 'home.html', {"error": error})
    return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="/static/base.css">
	</head>

	<body>
		<div class="container">

			<div class="row">
				<div class="mx-auto col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item" 
								     class="form-control input-lg" 
								     placeholder="Enter a to-do item" />
							{% csrf_token %}
							{% if error %}
								<div class="form-group has-error">
									<span class="help-block">{{ error }}</span>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="mx-auto col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>

		</div>
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}